#https://github.com/SensorsINI/v2e : to check options
overwrite = True
unique_output_folder = False
out_filename = "events.h5"
davis_output = False
skip_video_output = False
dvs_exposure = "duration .033"
output_mode = "dvs128"
input_frame_rate = 120
input_slowmotion_factor = 1
disable_slomo = True
timestamp_resolution = 0.001
auto_timestamp_resolution = True
slomo_model = "/content/v2e/input/SuperSloMo39.ckpt"
condition = "Clean"
thres = 0.2
sigma = 0.02
cutoff_hz = 0
leak_rate_hz = 0
shot_noise_rate_hz = 0
